---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wwwmayam/mayam-api
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - source $DEPLOYPATH/virtualenv/bin/activate && pip install -r $DEPLOYPATH/requirements.txt
    - /usr/bin/touch $DEPLOYPATH/tmp/restart.txt
